In [1]:
import pandas as pd

In [26]:
# df = pd.read_csv('D:\\서울시신호\\데이터\\검지기데이터\\A-도심.txt', nrows=30, encoding='cp949', sep=('\t' or ','))
# df

# import pandas as pd

# 파일 경로
file_path = 'D:\\서울시신호\\데이터\\검지기데이터\\A-도심.txt'

# 헤더 읽기
with open(file_path, 'r', encoding='cp949') as f:
    header_line = f.readline().strip()
headers = header_line.split('\t')

# 데이터 읽기
data = pd.read_csv(file_path, delimiter=',', skiprows=1, names=headers, encoding='cp949')

data

,REALTIME_ID,LOCATION,INITLANE,AHEAD,COLLECT_DATE,VOLUME,OCCUPANCY,SPEED
0,'A-01','성산로(금화터널)','1','유입','2023-06-01 00:00:00','0','0','0'
1,'A-01','성산로(금화터널)','1','유입','2023-06-01 00:00:30','0','0','0'
2,'A-01','성산로(금화터널)','1','유입','2023-06-01 00:01:00','0','0','0'
3,'A-01','성산로(금화터널)','1','유입','2023-06-01 00:01:30','0','0','0'
4,'A-01','성산로(금화터널)','1','유입','2023-06-01 00:02:00','0','0','0'
...,...,...,...,...,...,...,...,...
26531183,'A-23','소월로(회현역)','1','유출','2023-08-30 23:57:30','0','0','0'
26531184,'A-23','소월로(회현역)','1','유출','2023-08-30 23:58:00','0','0','0'
26531185,'A-23','소월로(회현역)','1','유출','2023-08-30 23:58:30','0','0','0'
26531186,'A-23','소월로(회현역)','1','유출','2023-08-30 23:59:00','1','2.82','0'
26531187,'A-23','소월로(회현역)','1','유출','2023-08-30 23:59:30','0','0','0'

In [27]:
data.SPEED.unique()

array(["'0'", "'44'", "'32'", "'51'", "'33'", "'46'", "'48'", "'28'",
       "'17'", "'57'", "'49'", "'54'", "'59'", "'47'", "'37'", "'41'",
       "'52'", "'40'", "'38'", "'61'", "'35'", "'36'", "'50'", "'45'",
       "'72'", "'42'", "'31'", "'43'", "'55'", "'56'", "'23'", "'34'",
       "'53'", "'21'", "'24'", "'64'", "'25'", "'39'", "'63'", "'58'",
       "'22'", "'70'", "'26'", "'68'", "'84'", "'29'", "'80'", "'12'",
       "'30'", "'9'", "'16'", "'11'", "'19'", "'14'", "'8'", "'13'",
       "'27'", "'15'", "'20'", "'18'", "'6'", "'7'", "'5'", "'10'", "'1'",
       "'4'", "'62'", "'66'", "'71'", "'69'", "'82'", "'81'", "'67'",
       "'60'", "'78'", "'2'", "'3'", "'75'", "'77'", "'65'", "'74'",
       "'73'", "'100'", "'90'", "'96'", "'76'", "'83'", "'86'", "'95'",
       "'85'", "'160'", "'89'", "'79'", "'88'", "'91'", "'92'", "'103'",
       "'142'", "'97'", "'98'", "'108'", "'101'", "'87'", "'93'", "'94'",
       "'102'", "'107'", "'104'", "'111'", "'114'", "'99'", "'105'",
       "'147'", "'134'", "'119'", "'117'", "'121'", "'115'", "'157'",
       "'133'", "'131'", "'109'", "'136'", "'112'", "'113'", "'139'",
       "'143'", "'106'", "'116'", "'110'", "'123'", "'153'", "'126'",
       "'130'", "'129'", "'125'", "'132'", "'120'", "'128'", "'158'",
       "'122'", "'146'", "'124'", "'135'", "'127'", "'141'", "'150'",
       "'118'", "'152'", "'138'", "'149'", "'155'", "'140'", "'156'"],
      dtype=object)